service: vishal-dynamodb
frameworkVersion: "3"
configValidationMode: error
provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:ap-south-1:738146172566:table/vishal-dynamo-db-assignment
    - Effect: Allow
      Action:
        - cognito-idp:*
      Resource:
        - arn:aws:cognito-idp:ap-south-1:738146172566:userpool/ap-south-1_4SBsLHW2M
plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  signup:
    handler: src/userPool/signUp.handler
    events:
      - httpApi:
          path: /signup
          method: post
  login:
    handler: src/userPool/login.handler
    events:
      - httpApi:
          path: /login
          method: post
    
  addUserToDataBase:
    handler: src/userPool/addUserToDataBase.handler
    events:
      - cognitoUserPool:
          pool: ravi-DemoPage
          trigger: PostConfirmation
          existing: true
  customMessage:
    handler: src/userPool/customMesssage.handler
    events:
      - cognitoUserPool:
          pool: ravi-DemoPage
          trigger: CustomMessage
          existing: true
  verifySignUp:
    handler: src/userPool/verfySignUp.handler
    events:
      - httpApi:
          path: /verfy-signup
          method: post
