service: vishal-dynamodb

frameworkVersion: "3"
configValidationMode: error

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:Query"
            - "dynamodb:Scan"
            - "dynamodb:GetItem"
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"

          Resource:
            - Fn::GetAtt:
                - vishalDynamoDBTableA
                - Arn

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

functions:
  login:
    handler: src/handler.login
    events:
      - httpApi:
          path: /users/login
          method: post
  hello:
    handler: src/dbHandler.hello
    events:
      - httpApi:
          path: /users/create
          method: get
  addEmployee:
    handler: src/dbHandler.addEmployee
  updateEmployee:
    handler: src/dbHandler.updateEmployee
  deleteEmployee:
    handler: src/dbHandler.deleteEmployee
  getEmployeeById:
    handler: src/dbHandler.getEmployee
  getAllEmployees:
    handler: src/dbHandler.getAllEmployees

resources:
  Resources:
    vishalDynamoDBTableA:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: vishalDynamoDBTableA
        AttributeDefinitions:
          - AttributeName: employeeType
            AttributeType: S
          - AttributeName: employeeId
            AttributeType: S

        KeySchema:
          - AttributeName: employeeType
            KeyType: HASH
          - AttributeName: employeeId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
